# Set to 4 to place the checkpoint item in the center slot of the hotbar
checkpointSlot: 3

# Set to a custom checkpoint item (i.e. ARROW, HEAVY_WEIGHTED_PRESSURE_PLATE)
checkpointItem: PRISMARINE_SHARD

# Set the reset item position in the hotbar
resetSlot: 4

# Set to a custom reset item (i.e. BLAZE_POWDER, COMPARATOR)
resetItem: RED_BED

# Set the leave item position in the hotb ar
cancelSlot: 5

# Set to a custom cancel item (i.e. BARRIER)
cancelItem: OAK_DOOR

# Allow players to skip a checkpoint during a parkour game
skipCheckpoints: false

# Send player to the beginning of the parkour on leave
returnToStart: false

# Remove all player effects upon a parkour game start
clearAllEffects: true

# Disallows players to collide with each other during parkour
disableCollisions: true

# Teleport players back to their latest checkpoint if they fall below the configured Y-level
# Useful for parkour courses built in or above the void.
voidTeleport:
  enabled: false
  y-axis: 48