# Set to 4 to place the checkpoint item in the center slot of the hotbar
checkpointSlot: 4

# Set the reset item position in the hotbar
resetSlot: 5

# Set the leave item position in the hotbar
leaveSlot: 0

# Allow players to skip a checkpoint during a parkour game
skipCheckpoints: false

# Send player to the beginning of the parkour on leave
returnToStart: false

# Remove all player effects upon a parkour game start
clearAllEffects: true

# Disallows players to collide with each other during parkour
disableCollisions: true