name: ParkourEX
author: 0x3mr
version: '1.0-SNAPSHOT'
main: org.zeroxamr.parkourEX.Main
api-version: '1.21'
commands:
  parkourex:
    aliases: [ pk, px, pkx ]
    description: Plugin description & instructions